### ISSUE TITLE
hide_when_no_warning broken?

### ISSUE THREAD

**Issue by CumpsD** [MrBartusek/MeteoalarmCard#180]
### Describe the bug

After upgrading to 2.5.0 it seems `hide_when_no_warning` is broken. I have it enabled, yet it still shows the card even when there are no warnings.

### Screenshots

![image](https://github.com/MrBartusek/MeteoalarmCard/assets/1201644/c6d016d2-2a84-4c43-a28a-c8a609f91d3f)

### Card version

v2.5.0

### Installation type

Home Assistant Community Store (HACS)

### Card Configuration

```yaml
type: custom:meteoalarm-card
entities: binary_sensor.meteoalarm
integration: meteoalarm
override_headline: false
hide_when_no_warning: true
tap_action:
  action: url
  url_path: https://www.meteo.be/nl/weer/waarschuwingen/overzichtskaart-belgie
```

### Integration type

Meteoalarm

**Comment by CumpsD** [comment]
Reverting to 2.4.3 fixes it:

![image](https://github.com/MrBartusek/MeteoalarmCard/assets/1201644/938ae38e-aa1e-4788-9280-172eeb5dbcdc)

**Comment by MrBartusek** [comment]
Yeah seams like it, will patch

**Comment by CumpsD** [comment]
Not related, but: is it possible to patch out the `s.entries is not a function` warning as well? ;)

**Comment by MrBartusek** [comment]
> Not related, but: is it possible to patch out the `s.entries is not a function` warning as well? ;)

possibly, I need screenshot from browser developer console

**Comment by CumpsD** [comment]
> > Not related, but: is it possible to patch out the `s.entries is not a function` warning as well? ;)
> 
> possibly, I need screenshot from browser developer console

No errors there:

![image](https://github.com/MrBartusek/MeteoalarmCard/assets/1201644/3590cff6-1c1a-402d-bba0-3c30531323e1)

**Comment by MrBartusek** [comment]
This will be fixed in the next version, thank you for your contribution!

For that editor bug, no idea honestly, can't reproduce it. You can try to remove the card and configure it via the visual editor and see if it breaks.

![image](https://github.com/MrBartusek/MeteoalarmCard/assets/23432278/df47f608-eeaa-4957-a3c3-ff8e0d1bea50)

![image](https://github.com/MrBartusek/MeteoalarmCard/assets/23432278/bef48827-6e9d-40e8-a10d-1dae647074f3)
